version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: students
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"

  app:
    build: .
    environment:
      DB_URL: jdbc:mysql://db:3306/students
      DB_USER: user
      DB_PASS: pass
    depends_on:
      - db
